# Generated by Django 5.2.10 on 2026-01-18 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('JITBIT', 'Jitbit'), ('JIRA', 'Jira'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(default='MEDIUM', max_length=30)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='core.mecontract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='SLABreachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breach_type', models.CharField(choices=[('RESPONSE', 'Response Time'), ('RESOLUTION', 'Resolution Time')], max_length=20)),
                ('breach_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaches', to='sla.servicerequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sla_breaches', to='tenancy.tenant')),
            ],
        ),
    ]
