# Generated by Django 5.2.10 on 2026-02-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sla", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(default="OPEN", max_length=50),
        ),
    ]
