# Generated by Django 5.2.10 on 2026-02-19 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_tenant_slug_alter_tenantuser_role"),
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowStateAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("SEND_EMAIL", "Send Email"),
                            ("UPDATE_FIELD", "Update Model Field"),
                        ],
                        max_length=30,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="workflows.workflowstate",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_state_actions",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="workflows.workflowdefinition",
                    ),
                ),
            ],
            options={
                "unique_together": {("workflow", "state", "name")},
            },
        ),
    ]
