# Generated by Django 5.2.10 on 2026-02-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tenantuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("PLATFORM_ADMIN", "Platform Admin"),
                    ("ME_LEAD", "ME Lead"),
                    ("FINANCE", "Finance"),
                    ("VIEWER", "Viewer"),
                ],
                default="VIEWER",
                max_length=20,
            ),
        ),
    ]
