# Generated by Django 5.2.10 on 2026-01-18 11:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MEOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_in_me', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='me_owners', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MicroEnterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('me_type', models.CharField(default='NODE_ME', max_length=20)),
                ('status', models.CharField(default='INCUBATION', max_length=20)),
                ('autonomy_level', models.CharField(default='RESTRICTED', max_length=20)),
                ('value_proposition', models.TextField(blank=True)),
                ('owners', models.ManyToManyField(related_name='micro_enterprises', through='core.MEOwner', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='micro_enterprises', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='meowner',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_links', to='core.microenterprise'),
        ),
        migrations.CreateModel(
            name='MEKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='me_kpis', to='tenancy.tenant')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpis', to='core.microenterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MEContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(default='DRAFT', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='me_contracts', to='tenancy.tenant')),
                ('consumer_me', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumed_contracts', to='core.microenterprise')),
                ('provider_me', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provided_contracts', to='core.microenterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SLATemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('response_time_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_time_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('availability_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sla_templates', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VAMAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('total_committed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vam_agreements', to='core.microenterprise')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vam_agreements', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='meowner',
            unique_together={('me', 'user')},
        ),
    ]
