# Generated by Django 5.2.10 on 2026-01-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecontract',
            name='sla_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.slatemplate'),
        ),
        migrations.AddField(
            model_name='microenterprise',
            name='cost_center',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='microenterprise',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
