# Generated by Django 5.2.10 on 2026-01-20 06:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_microenterprisestatus_alter_microenterprise_status_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='slatemplate',
            unique_together={('tenant', 'name')},
        ),
        migrations.CreateModel(
            name='MEService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('provider_me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.microenterprise')),
                ('sla_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.slatemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='me_services', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mecontract',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.meservice'),
        ),
    ]
