# Generated by Django 5.2.10 on 2026-01-20 06:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_slatemplate_name_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mecontract',
            name='service',
        ),
        migrations.CreateModel(
            name='ContractService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_services', to='core.mecontract')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_links', to='core.meservice')),
                ('sla_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.slatemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_services', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mecontract',
            name='services',
            field=models.ManyToManyField(related_name='contracts', through='core.ContractService', to='core.meservice'),
        ),
    ]
