# Generated by Django 5.2.10 on 2026-01-20 07:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_mecontract_service_contractservice_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_statuses', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'Contract statuses',
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AlterField(
            model_name='mecontract',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.contractstatus'),
        ),
    ]
