# Generated by Django 5.2.10 on 2026-01-26 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contractstatus_alter_mecontract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractservice',
            name='billing_type',
            field=models.CharField(choices=[('QUANTITY', 'Quantity'), ('PERIOD', 'Period')], default='PERIOD', max_length=20),
        ),
        migrations.AddField(
            model_name='contractservice',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractservice',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractservice',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='meservice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='core.meservice'),
        ),
    ]
