# Generated by Django 5.2.10 on 2026-01-26 10:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contractservice_billing_type_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSLACost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_costs', to='core.meservice')),
                ('sla_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_costs', to='core.slatemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_sla_costs', to='tenancy.tenant')),
            ],
            options={
                'unique_together': {('service', 'sla_template')},
            },
        ),
    ]
