# Generated by Django 5.2.10 on 2026-02-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_serviceslacost"),
        ("tenancy", "0002_tenant_slug_alter_tenantuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mecontract",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="mekpi",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="microenterprise",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vamagreement",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="mecontract",
            unique_together={("tenant", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="mekpi",
            unique_together={("tenant", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="microenterprise",
            unique_together={("tenant", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="vamagreement",
            unique_together={("tenant", "code")},
        ),
    ]
