# Generated by Django 5.2.10 on 2026-02-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_mecontract_code_alter_mekpi_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mecontract",
            name="status",
            field=models.CharField(default="DRAFT", max_length=50),
        ),
    ]
